name: DiscordChatWorldWhitelist
version: '${project.version}'
main: io.github.dinty1.discordchatworldwhitelist.DiscordChatWorldWhitelist
api-version: 1.15
depend: [ DiscordSRV ]
authors: [ Dinty1 ]
description: Restricts DiscordSRV Discord->Minecraft messages to certain worlds
